#!/bin/bash

set -euo pipefail

. shell-terminfo
. shell-getopt

terminfo_init

PROG="dc-preinstall-diag"
VERSION=0.2.8
verbose=
listcmd=
runcmd=run
logfile=/dev/null
force=
global_retval=0

print_version(){
    cat <<EOF
Версия программы $PROG - $PROG_VERSION
EOF
    exit
}

show_usage(){
    cat <<EOF
$PROG - утилита для проверки конфигурации системы для установки контроллера домена.

Формат вызова: $PROG [options] [<diagnostic-task>]

Опции:
-l, --list		Список диагностических задач
-V, --version		Вывод версии утилиты
-v, --verbose		Подробный вывод
-h, --help		Показать данную справку и выйти
-w, --logfile[=FILE]	Вывести подробный вывод в файл
-f, --force		Принудительная запись вывода в существующий файл
EOF
    exit
}

TEMP=$(getopt -n "$PROG" -o "l,V,v,h,w::,f" -l "list,version,verbose,help,logfile::,force" -- "$@") || show_usage
eval set -- "$TEMP"

while :; do
    case "$1" in
	-l|--list) listcmd=1 ;;
	-V|--version) print_version "$PROG" ;;
	-v|--verbose) verbose=1 ;;
	-h|--help) show_usage ;;
	-w|--logfile) shift; test -n "$1" && logfile="$1" || logfile="dc-preinstall-diag.log" ;;
	-f|--force) force=1 ;;
	--) shift; break ;;
	*) fatal "Unrecognized option: $1" ;;
    esac
    shift
done

customcmd="$*"

msg_fail(){
    echo -n "$*: ["
    color_text "FAIL" red
    echo "]"
}

msg_warn(){
    echo -n "$*: ["
    color_text "WARN" yellow
    echo "]"
}

msg_done(){
    echo -n "$*: ["
    color_text "DONE" green
    echo "]"
}

__command_msg(){
    local p='$'
    if test "$1" = '-r'; then
        shift
        p='#'
    fi
    color_message "$p $*" bold
}

__header(){
    color_message "===============================================================================" bold white
}

__footer(){
    color_message "===============================================================================" bold white
}

__delimiter(){
    echo "-------------------------------------------------------------------------------"
}

__check_title(){
    color_message "$1" bold white
}

__newline(){
    echo
}

__short_msg(){
    case "$1" in
        0) msg_done  "$2" ;;
        2) msg_warn  "$2" ;;
        102) msg_non_root  "$2" ;;
        *) msg_fail "$2" ;;
    esac
}

__log(){
    test -z $verbose && tee -a "$logfile" 1>/dev/null 2>&1 || tee -a "$logfile"
}

__log_force_print(){
    tee -a "$logfile"
}

print_head(){
    __header | __log
    __check_title "| Samba environment diagnostic tool |" | __log
    __delimiter | __log
    echo "Version: $VERSION" | __log
    echo "Date: $(date)" | __log
    __delimiter | __log
    echo "System information" | __log
    echo "Kernel: $(uname -r)" | __log
    echo "Branch: $(apt-repo list | cut -d ' ' -f 2 | grep -e '^\[.*\]$' | tail -1 | sed -E 's/\[(.*)\]/\1/')" | __log
    __footer | __log
    __newline | __log
}

_command(){
    local retval=0
    local x=
    local q=
    local r=
    if test "$1" = '-q'; then
        shift
        q=1
    fi
    if test "$1" = '-r'; then
        shift
        r=1
    fi
    if test "$1" = '-x'; then
        shift
        x=1
    fi
    test -z "$q" && test -z "$r" && __command_msg "$*"
    test -z "$q" && test -n "$r" && __command_msg -r "$*"
    test -z "$x" || echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    eval "$*" || retval=$?
    test -z "$x" || echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    echo
    return $retval
}

run(){
    local retval=126
    local func="$1"
    local msg
    msg=$(printf "| %s |" "$func")

    __header | __log

    __check_title "$msg" | __log
    __delimiter | __log
    __newline | __log

    $func 2>&1 | __log && retval=0 || retval=$?

    __delimiter | __log

    __short_msg $retval "$2" | __log_force_print

    __footer | __log
    __newline | __log
    return $retval
}

# Проверка наличия пакета task-samba-dc
check_task_samba_dc(){
    local retval=0
    local packet_name="task-samba-dc"
    local policy_output="$(apt-cache policy "$packet_name" 2> /dev/null)"
    local installed_version="$(echo "$policy_output" | grep "Установлен:" | awk '{print $2}')"

    if [ -z "$installed_version" ]; then
	echo -e "Пакет "$packet_name" не установлен в системе.\n"
	retval=2
    else
	echo -e "Пакет "$packet_name" установлен в системе. Версия пакета: "$installed_version".\n"
    fi

    return $retval
}

check_active_services(){
    local retval=0
    local retvals=()

    local service1="smb.service"
    local service2="nmb.service"
    local service3="krb5kdc.service"
    local service4="slapd.service"

    _command systemctl status "$service1" 2> /dev/null | head -n 1
    echo "$(systemctl status "$service1" 2> /dev/null)" | grep "Active: active (running)" && retvals[0]=0 ||
    { echo "$(systemctl status "$service1" 2> /dev/null)" | grep "Active: inactive (dead)" && retvals[0]=2; } ||
    { echo "$(systemctl status "$service1" 2> /dev/null)" | grep "Active: failed" && retvals[0]=1; } ||
    { echo "Ошибка: возможно служба отсутствует." && retvals[0]=1; }
    echo

    _command systemctl status "$service2" 2> /dev/null | head -n 1
    echo "$(systemctl status "$service2" 2> /dev/null)" | grep "Active: active (running)" && retvals[1]=0 ||
    { echo "$(systemctl status "$service2" 2> /dev/null)" | grep "Active: inactive (dead)" && retvals[1]=2; } ||
    { echo "$(systemctl status "$service2" 2> /dev/null)" | grep "Active: failed" && retvals[1]=1; } ||
    { echo "Ошибка: возможно служба отсутствует." && retvals[1]=1; }
    echo

    _command systemctl status "$service3" 2> /dev/null | head -n 1
    echo "$(systemctl status "$service3" 2> /dev/null)" | grep "Active: active (running)" && retvals[2]=0 ||
    { echo "$(systemctl status "$service3" 2> /dev/null)" | grep "Active: inactive (dead)" && retvals[2]=2; } ||
    { echo "$(systemctl status "$service3" 2> /dev/null)" | grep "Active: failed" && retvals[2]=1; } ||
    { echo "Ошибка: возможно служба отсутствует." && retvals[2]=1; }
    echo

    _command systemctl status "$service4" 2> /dev/null | head -n 1
    echo "$(systemctl status "$service4" 2> /dev/null)" | grep "Active: active (running)" && retvals[3]=0 ||
    { echo "$(systemctl status "$service4" 2> /dev/null)" | grep "Active: inactive (dead)" && retvals[3]=2; } ||
    { echo "$(systemctl status "$service4" 2> /dev/null)" | grep "Active: failed" && retvals[3]=1; } ||
    { echo "Ошибка: возможно служба отсутствует." && retvals[3]=1; }
    echo

    for val in "${retvals[@]}"; do
	if [[ $val -eq 1 ]]; then
	    retval=1
	    break
	elif [[ $val -eq 2 ]] && [[ $retval -ne 1 ]]; then
	    retval=2
	elif [[ $val -eq 0 ]] && [[ $retval -ne 1 ]] && [[ $retval -ne 2 ]]; then
	    retval=0
	fi
	done

    return $retval
}

check_samba_config(){
    local retval=0
    local file_config="/etc/samba/smb.conf"

    command test -s "$file_config" | head -n 1
    test -s "$file_config" && echo -e "Файл "$file_config" существует.\n" || { echo -e "Отсутствует файл "$file_config".\n" && retval=2; }

    return $retval
}

check_hostname(){
    local retval=0
    local host="$(hostname -f)"

    echo "Полное доменное имя хоста (FQDN):"
    echo -e ""$host"\n"

    { [[ "$host" == *.* ]] && [[ "$host" != $.* ]] && [[ "$(host "$host")" ]]; } || { echo "Некорректное доменное имя." && retval=2; }

    return $retval
}

check_local_in_domain_name(){
    local retval=0
    local host="$(hostname -f)"
    local suffix=".local"

    echo "Полное доменное имя хоста (FQDN):"
    echo -e ""$host"\n"

    [[ "$host" != *"$suffix"* ]] && echo -e "Доменное имя не содержит суффикс "$suffix".\n" || { echo -e "Доменное имя содержит суффикс "$suffix".\n" && retval=2; }

    return $retval
}

check_status_network_manager(){
    # Тут важный момент: могут использоваться настройки, не связанные с Network Manager, тогда тест будет неактуален.
    local retval=0
    local service="NetworkManager.service"

    _command systemctl status "$service" 2> /dev/null | head -n 1
    echo "$(systemctl status "$service" 2> /dev/null)" | grep "Active: active (running)" && retval=0 ||
    { echo "$(systemctl status "$service" 2> /dev/null)" | grep "Active: inactive (dead)" && retval=2; } ||
    { echo "$(systemctl status "$service" 2> /dev/null)" | grep "Active: failed" && retval=1; } ||
    { echo "Ошибка: возможно служба отсутствует." && retval=1; }
    echo

    return $retval
}

check_nameserver(){
    local retval=0
    local ip_addr="$(hostname -i)"
    local nameservers="$(grep "nameserver " /etc/resolv.conf | awk '{print $2}')"

    if echo "$nameservers" | grep -q "^$ip_addr$" || echo "$nameservers" | grep -q "127.0.0.1"; then
	echo -e "В конфигурационном файле "/etc/resolv.conf" имеется строка nameserver 127.0.0.1 или с адресом текущего сетевого интерфейса:\n$(grep "nameserver" /etc/resolv.conf)"
    else
	echo "В конфигурационном файле "/etc/resolv.conf" нет строки "nameserver" <ip_адрес_текущей_машины>"
	retval=2
    fi
	echo

    return $retval
}

default_run(){
    local retval=0

    run "$1" "$2" || retval=$?
    test $retval = 1 && global_retval=1
    return 0
}

list_run(){
    test -z $verbose &&
    echo "$1" ||
    echo "$1: $2"
}

custom_run(){
    if echo "$customcmd"  | tr ' ' '\n' | grep -q "^$1\$"; then
	run "$1" "$2" && global_retval=0 || global_retval=$?
    fi
}

init_log(){
    local log_index

    if test -e "$logfile" && test "$logfile" != "/dev/null" && test -z "$force"; then
	log_index="$(find . -maxdepth 1 -name "$logfile.*" 2>/dev/null | sort -V | tail -1 | sed -E 's/^.*\.([^.]*)$/\1/' || true)"
	logfile="$logfile".$(($log_index + 1))
    fi
    if test "$logfile" != "/dev/null"; then
	echo -n > "$logfile"
    fi
}

if ! test -z $listcmd; then
    runcmd=list_run
elif ! test -z "$customcmd"; then
    runcmd=custom_run
    global_retval=127
else
    runcmd=default_run
fi

if test -z $listcmd; then
    init_log
    print_head
fi

$runcmd check_task_samba_dc "Checking the availability of the "task-samba-dc" package"
$runcmd check_active_services "Checking running services: smb, nmb, krb5kdc, slapd"
$runcmd check_samba_config "Checking for the presence of the "/etc/samba/smb.conf" file"
$runcmd check_hostname "Checking the full domain name of the host (FQDN)"
$runcmd check_local_in_domain_name "Warning if there is a .local suffix in the name"
$runcmd check_status_network_manager "Information about the active Network interface manager"
$runcmd check_nameserver "Checking for nameserver 127.0.0.1 or <current_IP_address> in "/etc/resolv.conf""

test -f "$logfile" && test -w "$logfile" && sed -i 's/\x1b\[[0-9;]*[mGKH]//g' $logfile

exit "$global_retval"
