#!/bin/bash

set -euo pipefail

. shell-terminfo
. shell-getopt

terminfo_init

PROG="dc-preinstall-diag"
VERSION=0.2.8
verbose=
listcmd=
runcmd=run
logfile=/dev/null
force=
global_retval=0

print_version(){
    cat <<EOF
Версия программы $PROG - $PROG_VERSION
EOF
    exit
}

show_usage(){
    cat <<EOF
$PROG - утилита для проверки конфигурации системы для установки контроллера домена.

Формат вызова: $PROG [options] [<diagnostic-task>]

Опции:
-l, --list		Список диагностических задач
-V, --version		Вывод версии утилиты
-v, --verbose		Подробный вывод
-h, --help		Показать данную справку и выйти
-w, --logfile[=FILE]	Вывести подробный вывод в файл
-f, --force		Принудительная запись вывода в существующий файл
EOF
    exit
}

TEMP=$(getopt -n "$PROG" -o "l,V,v,h,w::,f" -l "list,version,verbose,help,logfile::,force" -- "$@") || show_usage
eval set -- "$TEMP"

while :; do
    case "$1" in
	-l|--list) listcmd=1 ;;
	-V|--version) print_version "$PROG" ;;
	-v|--verbose) verbose=1 ;;
	-h|--help) show_usage ;;
	-w|--logfile) shift; test -n "$1" && logfile="$1" || logfile="dc-preinstall-diag.log" ;;
	-f|--force) force=1 ;;
	--) shift; break ;;
	*) fatal "Unrecognized option: $1" ;;
    esac
    shift
done

customcmd="$*"

msg_fail(){
    echo -n "$*: ["
    color_text "FAIL" red
    echo "]"
}

msg_warn(){
    echo -n "$*: ["
    color_text "WARN" yellow
    echo "]"
}

msg_done(){
    echo -n "$*: ["
    color_text "DONE" green
    echo "]"
}
