#!/bin/bash

set -euo pipefail

. shell-terminfo
. shell-getopt

terminfo_init

PROG="dc-preinstall-diag"
VERSION=0.2.8
verbose=
listcmd=
runcmd=run
logfile=/dev/null
force=
global_retval=0

print_version(){
    cat <<EOF
Версия программы $PROG - $PROG_VERSION
EOF
    exit
}

show_usage(){
    cat <<EOF
$PROG - утилита для проверки конфигурации системы для установки контроллера домена.

Формат вызова: $PROG [options] [<diagnostic-task>]

Опции:
-l, --list<----><------>Список диагностических задач
-V, --version<-><------>Вывод версии утилиты
-v, --verbose<-><------>Подробный вывод
-h, --help<----><------>Показать данную справку и выйти
-w, --logfile[=FILE]<-->Вывести подробный вывод в файл
-f, --force<---><------>Принудительная запись вывода в существующий файл
EOF
    exit
}
